apiVersion: v1
kind: Service
metadata:
  name: retail-mlops-api
  labels:
    app: retail-mlops-api
spec:
  selector:
    app: retail-mlops-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000