global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "mlops-self-healing-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - mlops-api:8000